tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"

brew "bash-completion"
brew "curl"
brew "emacs"
brew "git"
brew "gnu-sed"

cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "slate"
cask "sonos-s1-controller"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
