tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "superfly/tap"

brew "bash-completion"
brew "curl"
brew "emacs"
brew "git"
brew "gnu-sed"
brew "superfly/tap/flyctl"

cask "docker"
cask "discord"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "slate"
cask "sonos-s1-controller"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
